#!/bin/bash

set -e

if [ x"$URL" == x"" ]; then URL="git://gforge01.dal.design.ti.com/linux-c6x/tactical-0.x"; fi
if [ x"$BRANCH" == x"" ]; then BRANCH="master"; fi
if [ x"$REMOTE" == x"" ]; then REMOTE="origin"; fi

BASE_PRJ="linux-c6x-project linux-c6x busybox uClibc"
WRAP_PRJ="ti-gcc-wrap/gdb ti-gcc-wrap/tool-wrap ti-gcc-wrap/sources"
TOP=..

cd $TOP
case $1 in
clone)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	mkdir -p $(dirname $prj)
	(cd $(dirname $prj); git clone $URL/$prj.git)
	(cd $prj; git checkout $BRANCH)
    done
;;
fetch)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	(cd $prj; git fetch $REMOTE)
    done
;;
pull)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	(cd $prj; git fetch $REMOTE)
	(cd $prj; git pull $REMOTE $BRANCH)
    done
;;
push)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	(cd $prj; git push $REMOTE $BRANCH:$BRANCH)
    done
;;
tag)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	(cd $prj; git tag $2)
    done
;;
status)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	echo "****** $prj"
	(cd $prj; git status)
    done
;;
push-tag)
    for prj in $BASE_PRJ $WRAP_PRJ ; do
	(cd $prj; git push tag $2)
    done
;;
*)
    echo "Don't know command $1"
    false
;;
esac




