#!/bin/bash
# Auto-generate requirements for executables (both ELF and a.out) and library
# sonames, script interpreters, and perl modules.
#

ulimit -c 0

#
# --- Grab the file manifest and classify files.
filelist=`sed "s/['\"]/\\\&/g"`
exelist=`echo $filelist | xargs -r file | egrep -v ":.* (commands|script)" | \
	grep ":.*executable" | cut -d: -f1`
scriptlist=`echo $filelist | xargs -r file | \
	egrep ":.* (commands|script)" | cut -d: -f1`
liblist=`echo $filelist | xargs -r file | \
	grep ":.*shared object" | cut -d : -f1`

interplist=
perllist=
pythonlist=
tcllist=

#
# --- Script interpreters.
for f in $scriptlist; do
    [ -r $f -a -x $f ] || continue
    interp=`head -1 $f | sed -e 's/^\#\![ 	]*//' | cut -d" " -f1`
    interplist="$interplist $interp"
    case $interp in
    */perl)	perllist="$perllist $f" ;;
    esac
done
[ -n "$interplist" ] && { echo "$interplist" | tr '[:blank:]' \\n | sort -u ; }

#
# --- Add perl module files to perllist.
for f in $filelist; do
    [ -r $f -a "${f%.pm}" != "${f}" ] && perllist="$perllist $f"
done

#
# --- Perl modules.
[ -x $SDK_C6X_DIR/rpm/lib/rpm/perl.req -a -n "$perllist" ] && \
    echo $perllist | tr '[:blank:]' \\n | $SDK_C6X_DIR/rpm/lib/rpm/perl.req | sort -u

#
# --- Python modules.
[ -x $SDK_C6X_DIR/rpm/lib/rpm/python.req -a -n "$pythonlist" ] && \
    echo $pythonlist | tr '[:blank:]' \\n | $SDK_C6X_DIR/rpm/lib/rpm/python.req | sort -u

#
# --- Tcl modules.
[ -x $SDK_C6X_DIR/rpm/lib/rpm/tcl.req -a -n "$tcllist" ] && \
    echo $tcllist | tr '[:blank:]' \\n | $SDK_C6X_DIR/rpm/lib/rpm/tcl.req | sort -u

exit 0
