#!/bin/bash

set -o pipefail
set -x
set -e

# set default values if vars not already defined
: ${SERVER_NAME:=cm-build}
: ${SSH_NAME:=cm-build}
: ${AT_END:=halt}

./release-build local-prep

virtual-server run $SERVER_NAME
scp release-build build.def setenv*.build $SSH_NAME:.

if [ -d manual-dependencies ] ; then
    rsync -av manual-dependencies $SSH_NAME:.
fi
if [ -d prep-resources ] ; then
    rsync -av prep-resources $SSH_NAME:.
fi

if [ -d output ] ; then
    rm -rf output
fi

ssh $SSH_NAME chmod +x release-build
if ssh $SSH_NAME -t ./release-build  2>&1 | tee ec2-build.raw.log ; then
    col -b -x <ec2-build.raw.log >ec2-build.log
    rsync -av $SSH_NAME:output .
else
    rc=$?
    echo "Job Failed rc=$rc"
fi

if [ x"$AT_END" != x"nop" ]; then
    virtual-server $AT_END $SERVER_NAME
fi

exit $rc
