#!/bin/sh
# Make a cpio archive from the specified directory
if [ -z "$1" ] || [ ! -d $1 ]; then 
    echo "need dir as arg1"; 
    exit 1
fi
rm -rf $1.cpio.gz
(cd $1; find . | cpio -H newc -o > ../$1.cpio)
gzip <$1.cpio >$1.cpio.gz



