#!/bin/sh
# Make an initial ramdisk from the $1 directory
if [ -z "$1" ] || [ ! -e $1.cpio.gz ] ; then 
    echo "need <arg1>.cpio.gz"; 
    exit 1
fi
if [ -e $1 -a -d $1 ] ; then
    rm -rf $1
fi
mkdir -p $1
if [ ! -d $1 ] ; then
    echo could not create dir $1
    exit 1
fi
echo This will require sudo access
sudo echo sudo worked
(cd $1; zcat ../$1.cpio.gz | sudo cpio -i)


