#!/bin/bash

CONFIGFILE=$1
ROOTFS=$2
COMPRESS=$3

/bin/sed -i -e "s,CONFIG_INITRAMFS_SOURCE=.*,CONFIG_INITRAMFS_SOURCE=\"${ROOTFS}.cpio\"," ${CONFIGFILE}

if [ "$COMPRESS" = "NONE" ]; then
  /bin/sed -i -e "s,# CONFIG_INITRAMFS_COMPRESSION_NONE.*,CONFIG_INITRAMFS_COMPRESSION_NONE=y," ${CONFIGFILE}
fi

if [ "$COMPRESS" = "GZIP" ]; then
  /bin/sed -i -e "s,# CONFIG_INITRAMFS_COMPRESSION_GZIP.*,CONFIG_INITRAMFS_COMPRESSION_GZIP=y," ${CONFIGFILE}
fi

if [ "$COMPRESS" = "BZIP2" ]; then
  /bin/sed -i -e "s,# CONFIG_INITRAMFS_COMPRESSION_BZIP2.*,CONFIG_INITRAMFS_COMPRESSION_BZIP2=y," ${CONFIGFILE}
fi

if [ "$COMPRESS" = "LZMA" ]; then
  /bin/sed -i -e "s,# CONFIG_INITRAMFS_COMPRESSION_LZMA.*,CONFIG_INITRAMFS_COMPRESSION_LZMA=y," ${CONFIGFILE}
fi

if [ "$COMPRESS" = "LZO" ]; then
  /bin/sed -i -e "s,# CONFIG_INITRAMFS_COMPRESSION_LZO.*,CONFIG_INITRAMFS_COMPRESSION_LZO=y," ${CONFIGFILE}
fi

